### PR TITLE
Abort on root count overflows

### LINKED ISSUE #34: Root count overflows in `mem::forget` loop, leading to erroneous drop
Running the following in release mode causes a segfault:

```rust
extern crate gc;

use gc::Gc;
use std::{mem, usize};

fn main() {
    let a = Gc::new("abc".to_string());
    let a2 = a.clone();

    for _ in 0..usize::MAX {
        mem::forget(a.clone());
    }

    drop(a2);
    gc::force_collect();
    println!("{:?}", *a);
}
```

This is the same issue that was fixed in rust-lang/rust#27174. I have a fix incoming.

### PR DESCRIPTION
**Pull request by apasel422**
Closes #34

### CODE REVIEW

File: gc/src/gc.rs [hunk 1]
```diff
@@ -114,7 +114,10 @@ impl<T: Trace + ?Sized> GcBox<T> {
     /// Roots prevent the GcBox from being destroyed by
     /// the garbage collector.
     pub unsafe fn root_inner(&self) {
-        self.header.roots.set(self.header.roots.get() + 1);
+        // abort if the count overflows to prevent `mem::forget` loops that could otherwise lead to
+        // erroneous drops
+        self.header.roots.set(self.header.roots.get()
```
Comment (Manishearth) [inline gc/src/gc.rs]: Panic should be ok?

Comment (apasel422) [inline gc/src/gc.rs]: Sure. I was just copying the behavior of `{Arc, Rc}`.

**Comment by Manishearth** [comment]
Fair. If they abort we should too.
